FROM node

ARG PORT=9615
ENV PORT=${PORT}

RUN apt update && apt install -y git
RUN git clone https://github.com/armoniax/amax.explorer.git && echo "v0.5"

RUN mv /amax.explorer/backend /opt/expsvr
RUN rm -rf /amax.explorer
WORKDIR /opt/expsvr

RUN npm update
RUN npm install -g pm2@2.10.4 express
RUN cd ./server && npm install

CMD ["pm2-runtime", "./server/ecosystem.config.js", "--web"]

EXPOSE ${PORT}
