FROM node

ARG CONFIG_NET=production
ENV CONFIG_NET=${CONFIG_NET}

RUN apt update && apt install -y git
RUN echo "v0.5.5" && git clone https://github.com/armoniax/amax.explorer.git
RUN cd /amax.explorer/frontend && npm install
RUN cd /amax.explorer/frontend && npm run build

FROM nginx
ARG PORT=80
ENV PORT=${PORT}

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/
RUN mkdir -p /opt/www/amax-explorer
COPY --from=0 /amax.explorer/frontend/dist/ /opt/www/amax-explorer/
EXPOSE ${PORT}